=== UASGeoZones/ED-318/schema/Schema_GeoZoneProperties.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "UASZoneVersion",
    "type": "object",
    "properties": {
        "identifier": {
            "type": "string",
            "maxLength": 7
        },
        "country": {
            "type": "string",
            "minLength": 3,
            "maxLength": 3
        },
        "name": {
            "type": "array",
            "items": {
                "minItems": 1,
                "$ref": "./Schema_GeoZoneDataTypes.json#/definitions/textShortType"
            }
        },
        "type": {"$ref": "./Schema_GeoZoneDataTypes.json#/definitions/zoneType"},
        "variant": {"$ref": "./Schema_GeoZoneDataTypes.json#/definitions/zoneVariant"},
        "restrictionConditions": {"type": "string"},
        "region": {"type": "integer"},
        "reason": {"$ref": "./Schema_GeoZoneDataTypes.json#/definitions/zoneReason"},
        "otherReasonInfo": {
            "type": "array",
            "items": {
                "minItems": 1,
                "$ref": "./Schema_GeoZoneDataTypes.json#/definitions/textShortType"
            }
        },
        "regulationExemption": {"$ref": "./Schema_GeoZoneDataTypes.json#/definitions/yesNoType"},
        "message": {
            "type": "array",
            "items": {
                "minItems": 1,
                "$ref": "./Schema_GeoZoneDataTypes.json#/definitions/textShortType"
            }
        },
        "zoneAuthority": {
            "type": "array",
            "items": {"$ref": "./Schema_GeoZoneAuthority.json"},
            "minItems": 1
        },
        "limitedApplicability": {
            "type": "array",
            "items": {"$ref": "./Schema_GeoZoneTimePeriod.json"}
        },
        "dataSource": {"$ref": "./Schema_GeoZoneDataTypes.json#/definitions/metadata"},
        "extendedProperties": {"type": "object"}
    },
    "required": [
        "identifier",
        "country",
        "type",
        "variant",
        "zoneAuthority"
    ],
    "additionalProperties": false
}

=== UASGeoZones/ED-318/examples/PartialExample_GeoZoneProperties.json
{
    "identifier": "NFZ6547",
    "country": "FRA",
    "name": [
        {"text": "LFPG-2",
        "lang": "en-GB"}
    ],
    "variant": "COMMON",
    "type": "REQ_AUTHORIZATION",
    "reason": [
        "AIR_TRAFFIC",
        "OTHER"
    ],
    "otherReasonInfo": [
        {
            "text": "Flying Whales - part 2",
            "lang": "en-GB"
        },
        {
            "text": "Baleines Volantes 2-Ã¨me partie",
            "lang": "fr-BE"
        }
    ],
    "limitedApplicability": [
        {
            "startDateTime": "2018-12-31T15:59:59Z",
            "endDateTime": "2019-12-31T15:59:59Z",
            "schedule": [
                {
                    "day": ["ANY"],
                    "startTime": "16:00:00Z",
                    "endTime": "17:00:00Z"
                },
                {
                    "day": ["SUN"],
                    "startTime": "10:00:00Z",
                    "endTime": "12:00:00Z"
                }
            ]
        }
    ],
    "zoneAuthority": [
        {
            "name": [
                {
                    "text": "LFPG-UASZoneManager",
                    "lang": "en-us"
                }
            ],
            "email": "UASZoneManager@lfpg.fr",
            "purpose": "AUTHORIZATION"
        }
    ]
}
